### ISSUE TITLE
Не работает метод валидатора matches

### ISSUE THREAD

**Issue by ultraviolet** [Pathologic/FormLister#96]
Параметр правил (упрощенная регулярка для теста, чтобы исключить её влияние на ошибку):
```
&rules=`{
  "phone": {
    "matches": {
      "params": "/^\d{2}$/",
      "message": "не две цифры"
    }
  }
}`
```

По отправке формы возвращает пустоту (не происходит вызова кода/шаблона, назначенного на успешную отправку формы), но письмо отправляется. 

Другие правила отрабатывают корректно - либо успешная отправка с вызовом соотв. кода/шаблона, либо вывод сообщения об ошибке.

Это у меня что-то слетело или есть такое дело?

**Comment by Pathologic** [comment]
Должно быть
```
\\d{2}
```

**Comment by ultraviolet** [comment]
Действительно, так работает:
`"params": "/^\\d{2}$/"`
Если без Аякса. А на Аяксе - почему-то - нет (изначально пробовал в регулярке экранировать обратный слеш на Аяксе, затем забыл перепроверить, отключив его). 
При этом, другие правила на Аяксе работают чётко (блокируется отправка и выводится сообщение об ошибке). 

Пример когда правила работают:
```
$modx->runSnippet('FormLister', array(
      'formid' => 'callme',
      'rules' => '{
        "phone": {
          "alpha": "нужны только буквы",
          "minLength": {
            "params": "5",
            "message": "не та длина"
          }
        }
      }',
      'formTpl' => 'callme-tpl',
      'to' =>'some@email.ru',
      'subject' => 'Обращение через форму обр. зв.',
      'reportTpl' => 'callme-report-tpl',
      'successTpl' => 'callme-success-tpl',
      'removeEmptyPlaceholders' => '1'
    ));
```

Пример с регуляркой, когда то же правило в matches не срабатывает:
```
$modx->runSnippet('FormLister', array(
      'formid' => 'callme',
      'rules' => '{
        "phone": {
          "matches": {
            "params": "/^\\d{2}$/",
            "message": "не две цифры"
          }
        }
      }',
      'formTpl' => 'callme-tpl',
      'to' =>'some@email.ru',
      'subject' => 'Обращение через форму обр. зв.',
      'reportTpl' => 'callme-report-tpl',
      'successTpl' => 'callme-success-tpl',
      'removeEmptyPlaceholders' => '1'
    ));
```

Где-то ошибаюсь?

PS: 
> По отправке формы возвращает пустоту

Тут ошибся (опечатка в названии чанка с шаблоном по успешной отправке) - всегда возвращается либо ошибка, либо происходит успешная отправка.

**Comment by Pathologic** [comment]
Раз вызов из php, то можно без json, сразу массив поставить и тогда одного слэша должно хватить

-------- Исходное сообщение --------
От: ultraviolet <notifications@github.com> 
Дата: 13.04.2018  10:46  (GMT+03:00) 
Кому: Pathologic/FormLister <FormLister@noreply.github.com> 
Копия: Pathologic <m@xim.name>, Comment <comment@noreply.github.com> 
Тема: Re: [Pathologic/FormLister] Не работает метод валидатора matches (#96) 

Действительно, так работает:

"params": "/^\\d{2}$/"

Если без Аякса. А на Аяксе - почему-то - нет (изначально пробовал в регулярке экранировать обратный слеш на Аяксе, затем забыл перепроверить, отключив его).

При этом, другие правила на Аяксе работают чётко (блокируется отправка и выводится сообщение об ошибке).
Пример когда правила работают:
$modx->runSnippet('FormLister', array(
      'formid' => 'callme',
      'rules' => '{
        "phone": {
          "alpha": "нужны только буквы",
          "minLength": {
            "params": "5",
            "message": "не та длина"
          }
        }
      }',
      'formTpl' => 'callme-tpl',
      'to' =>'some@email.ru',
      'subject' => 'Обращение через форму обр. зв.',
      'reportTpl' => 'callme-report-tpl',
      'successTpl' => 'callme-success-tpl',
      'removeEmptyPlaceholders' => '1'
    ));

Пример с регуляркой, когда то же правило в matches не срабатывает:
$modx->runSnippet('FormLister', array(
      'formid' => 'callme',
      'rules' => '{
        "phone": {
          "matches": {
            "params": "/^\\d{2}$/",
            "message": "не две цифры"
          }
        }
      }',
      'formTpl' => 'callme-tpl',
      'to' =>'some@email.ru',
      'subject' => 'Обращение через форму обр. зв.',
      'reportTpl' => 'callme-report-tpl',
      'successTpl' => 'callme-success-tpl',
      'removeEmptyPlaceholders' => '1'
    ));

Где-то ошибаюсь?
PS:

По отправке формы возвращает пустоту

Тут ошибся (опечатка в названии чанка с шаблоном по успешной отправке) - всегда возвращается либо ошибка, либо происходит успешная отправка.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pathologic/FormLister","title":"Pathologic/FormLister","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Pathologic/FormLister"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ultraviolet in #96: Действительно, так работает:\r\n`\"params\": \"/^\\\\d{2}$/\"`\r\nЕсли без Аякса. А на Аяксе - почему-то - нет (изначально пробовал в регулярке экранировать обратный слеш на Аяксе, затем забыл перепроверить, отключив его). \r\nПри этом, другие правила на Аяксе работают чётко (блокируется отправка и выводится сообщение об ошибке). \r\n\r\nПример когда правила работают:\r\n```\r\n$modx-\u003erunSnippet('FormLister', array(\r\n      'formid' =\u003e 'callme',\r\n      'rules' =\u003e '{\r\n        \"phone\": {\r\n          \"alpha\": \"нужны только буквы\",\r\n          \"minLength\": {\r\n            \"params\": \"5\",\r\n            \"message\": \"не та длина\"\r\n          }\r\n        }\r\n      }',\r\n      'formTpl' =\u003e 'callme-tpl',\r\n      'to' =\u003e'some@email.ru',\r\n      'subject' =\u003e 'Обращение через форму обр. зв.',\r\n      'reportTpl' =\u003e 'callme-report-tpl',\r\n      'successTpl' =\u003e 'callme-success-tpl',\r\n      'removeEmptyPlaceholders' =\u003e '1'\r\n    ));\r\n```\r\n\r\nПример с регуляркой, когда то же правило в matches не срабатывает:\r\n```\r\n$modx-\u003erunSnippet('FormLister', array(\r\n      'formid' =\u003e 'callme',\r\n      'rules' =\u003e '{\r\n        \"phone\": {\r\n          \"matches\": {\r\n            \"params\": \"/^\\\\d{2}$/\",\r\n            \"message\": \"не две цифры\"\r\n          }\r\n        }\r\n      }',\r\n      'formTpl' =\u003e 'callme-tpl',\r\n      'to' =\u003e'some@email.ru',\r\n      'subject' =\u003e 'Обращение через форму обр. зв.',\r\n      'reportTpl' =\u003e 'callme-report-tpl',\r\n      'successTpl' =\u003e 'callme-success-tpl',\r\n      'removeEmptyPlaceholders' =\u003e '1'\r\n    ));\r\n```\r\n\r\nГде-то ошибаюсь?\r\n\r\nPS: \r\n\u003e По отправке формы возвращает пустоту\r\n\r\nТут ошибся (опечатка в названии чанка с шаблоном по успешной отправке) - всегда возвращается либо ошибка, либо происходит успешная отправка.\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Pathologic/FormLister/issues/96#issuecomment-381053260"}}}

**Comment by ultraviolet** [comment]
К сожалению, на PHP могу только в режиме копипаста с небольшими отклонениями, поэтому не понимаю как оформить в виде массива. [Этот сервис](https://www.functions-online.com/json_decode.html) подсказал ($returnValue), что обратный слеш нужно экранировать зверским образом, что и сделал, и заработало. Итоговый код для вызова из PHP получился таким:
```
'rules' => '{
        "phone": {
          "matches": {
            "params": "/^\\\+7\\\\s?\\\\d{3}\\\\s?\\\\d{3}\\\\s?\\\\d{2}\\\\s?\\\\d{2}$/",
            "message": "Неверный формат номера"
          }
        }
      }'
```
Спасибо за помощь, сорри, что отнял время.
